Oxide/Oxide/Areas/Admin/Controllers/FrontController.cs
using System;
using System.Diagnostics;
using System.Globalization;
using System.Web.Mvc;
using Oxide.Core.Base.OxideAttributes;
using Oxide.Core.Base.OxideController;
using Oxide.Core.Extesions;
using Oxide.Core.Helpers;
using Oxide.Core.Managers.CacheManager;
using Oxide.Core.Managers.CultureManager;
using Oxide.Core.Managers.PageManager;
using Oxide.Core.Managers.ThemeManager;
using Oxide.Core.Models.Base;
using Oxide.Core.Models.Log;
using Oxide.Core.Services.LogService;
using Oxide.Core.Services.OxideService;
using Oxide.Core.Services.PageService;
using Oxide.Core.Services.Redirection;
using Oxide.Core.Syntax;
using Oxide.Core.ViewModels.GeneralViewModels;

namespace Oxide.Areas.Admin.Controllers
{
    public partial class FrontController : OxideController
    {
        private readonly ICultureManager _cultureManager;
        private readonly ILogService _logWriter;
        private readonly IPageManager _pageManager;
        private readonly IPageService _pageService;
        private readonly IRedirectionService _redirectionService;
        private readonly IThemeManager _themeManager;
        private readonly IOxideCacheManager _cacheManager;
        public FrontController()
        {
        }

        public FrontController(IOxideServices oxideServices, IPageService pageService, IThemeManager themeManager,
            IPageManager pageManager, ICultureManager cultureManager, ILogService logWriter,
            IRedirectionService redirectionService, IOxideCacheManager cacheManager) : base(oxideServices)
        {
            _pageService = pageService;
            _themeManager = themeManager;
            _pageManager = pageManager;
            _cultureManager = cultureManager;
            _logWriter = logWriter;
            _redirectionService = redirectionService;
            _cacheManager = cacheManager;
        }

        [Front]
        public virtual ActionResult Index()
        {
            var model = new OxideModel
            {
                RequestType = Syntax.Requests.Static,
                Header = OxideServices.GetText("Error"),
                Title = OxideServices.GetText("Page Error"),
                Parameters = ""
            };

            try
            {
                var currentCuture = _cultureManager.GetFrontCurrentCulture();
                var requestedUrl = System.Web.HttpContext.Current.Request.Url.LocalPath;

                //Check if there is any redirection settings
                string cacheName = $@"cacheRedirections_{requestedUrl}";
                string cacheNameTitle = $@"Redirection cache for {requestedUrl}";
                string cultureSettingsCacheName = "frontCultureSet";

                var url = requestedUrl;
                var redirectionSetting = _cacheManager.GetOrSet(cacheName, cacheNameTitle,
                 Constants.Redirections, () => _redirectionService.GetRedirection(url));

                if (redirectionSetting != null)
                {
                    Response.StatusCode = (int) redirectionSetting.StatusCode;

                    if (redirectionSetting.StatusCode == Syntax.RedirectionStatusCode.MovedPermanently)
                        Response.RedirectPermanent(redirectionSetting.NewUrl);

                    if (redirectionSetting.StatusCode == Syntax.RedirectionStatusCode.Found)
                        Response.Redirect(redirectionSetting.NewUrl);
                }

                var result = requestedUrl.IsUrlFinishWithSlash();

                if (result && !requestedUrl.IsBaseUrl())
                    requestedUrl = requestedUrl.ClearUrlFromSlash();

                var page = _pageService.GetPageWithLanguage(requestedUrl);

                //If the page requested with addtional slash, redirect it with status code 301 to the original page
                if (result && page != null && requestedUrl.Length > 1)
                    Response.StatusCode = 301;

                var orjPage = page;

                if (page != null)
                {
                    //Check if the client browser culture is same the with requested page culture
                    if (orjPage.Language.Code3 != currentCuture.ThreeLetterISOLanguageName)
                    {
                        //Check if there is page with the same culture which client browser has
                        orjPage = _pageService.GetPage(requestedUrl, currentCuture.ThreeLetterISOLanguageName);
                        if (orjPage != null)
                        {
                            if (orjPage.Published && orjPage.VisibleForSite)
                                Response.Redirect(orjPage.Url);
                            else
                            {
                                Response.StatusCode = 404;
                                return View(_themeManager.GetErrorPage(ErrorTypes.Error404), model);
                            }
                        }
                        else
                            //Write page culture into client cookie, so all other operations related with the culture can be done correctly because setting culture as default
                            _cultureManager.SetFrontCulture(new CultureInfo(page.Language.Code), Response);

                    }
                    if (page.Published && page.VisibleForSite)
                        return View(_themeManager.GetMainLayout(page.MainLayoutId),
                            _pageManager.GetRenderPageModel(page));
                    Response.StatusCode = 404;
                    return View(_themeManager.GetErrorPage(ErrorTypes.Error404), model);
                }
                Response.StatusCode = 404;
                return View(_themeManager.GetErrorPage(ErrorTypes.Error404), model);
            }
            catch (Exception ex)
            {
                var log = new Log
                {
                    DateTimeInfo = DateTime.Now,
                    LogType = Syntax.LogTypes.Error,
                    Title = ex.Message,
                    ModuleName = OxideUtils.GetCallerModuleName(new StackFrame(1)),
                    Description = ex.StackTrace
                };
                if (ex.InnerException != null)
                    log.InnerException = ex.InnerException.Message;
                _logWriter.CreateLog(log);
            }
            Response.StatusCode = 404;
            return View(_themeManager.GetErrorPage(ErrorTypes.Error404), model);
        }
    }
}

Oxide/Oxide/Areas/Admin/Controllers/WidgetController.cs
using System.Linq;
using System.Web.Mvc;
using Oxide.Areas.Admin.ViewModels;
using Oxide.Core.Base.OxideAttributes;
using Oxide.Core.Base.OxideController;
using Oxide.Core.Managers.WidgetManager;
using Oxide.Core.Models;
using Oxide.Core.Models.Base;
using Oxide.Core.Services.OxideService;
using Oxide.Core.Services.WidgetService;
using Oxide.Core.Syntax;

namespace Oxide.Areas.Admin.Controllers
{
    public partial class WidgetController : OxideController
    {
        private readonly IWidgetManager _widgetManager;
        private readonly IWidgetService _widgetService;

        public WidgetController()
        {
        }

        public WidgetController(IOxideServices oxideServices, IWidgetService widgetService, IWidgetManager widgetManager)
            : base(oxideServices)
        {
            _widgetService = widgetService;
            _widgetManager = widgetManager;
        }

        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Display Widgets",
            Key = PermissionKeys.CanDisplayWidgets)]
        public virtual ActionResult DisplayWidgets()
        {
            return
                View(new OxideModel
                {
                    RequestType = Syntax.Requests.Static,
                    Header = OxideServices.GetText("Widgets"),
                    Title = Constants.Empty
                });
        }

        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Edit Widgets",
            Key = PermissionKeys.CanEditWidgets)]
        public virtual ActionResult EditRegularWidget(int widgetId, int pageId)
        {
            var editWidgetViewModel = new EditWidgetViewModel
            {
                PageId = pageId,
                WidgetData = _widgetService.GetPageWidget(widgetId)
            };
            return
                View(new OxideModel
                {
                    RequestType = Syntax.Requests.Static,
                    Header = OxideServices.GetText("Edit Widget"),
                    Title = Constants.Empty,
                    Parameters = editWidgetViewModel
                });
        }

        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Edit Widgets",
            Key = PermissionKeys.CanEditWidgets)]
        public virtual ActionResult EditMainLayoutWidget(int widgetId, int pageId, string layoutName)
        {
            var editWidgetViewModel = new EditMainLayoutWidgetViewModel
            {
                PageId = pageId,
                WidgetData = _widgetService.GetMainLayoutWidget(widgetId),
                LayoutName = layoutName
            };
            return
                View(new OxideModel
                {
                    RequestType = Syntax.Requests.Static,
                    Header = OxideServices.GetText("Edit Widget"),
                    Title = Constants.Empty,
                    Parameters = editWidgetViewModel
                });
        }

        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Manage Widgets",
            Key = PermissionKeys.CanManageWidgets)]
        public virtual ActionResult UpdateRegularWidget(string title, int widgetId, int pageId)
        {
            _widgetService.UpdateWidgetTitle(widgetId, title);
            return RedirectToAction(MVC.Admin.Page.ActionNames.ManageWidgets, MVC.Admin.Page.Name,
                new {Area = T4MVCHelpers.DefaultArea(), pageId});
        }

        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Manage Widgets",
            Key = PermissionKeys.CanManageWidgets)]
        public virtual ActionResult UpdateMainLayoutWidget(string title, int widgetId, int pageId, string layoutName)
        {
            _widgetService.UpdateMainLayotWidgetTitle(widgetId, title);
            return RedirectToAction(MVC.Admin.Layouts.ActionNames.ManageWidgets, MVC.Admin.Layouts.Name,
                new {Area = T4MVCHelpers.DefaultArea(), mainLayoutId = pageId, layoutName});
        }

        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Manage Widgets",
            Key = PermissionKeys.CanManageWidgets)]
        public virtual ActionResult RenderWidgetAdmin(string widgetKey, int widgetId, int containerPageId, int layoutId,
            int layoutKeyId, string dynamicTitle, string successMessage = null, string errorMessage = null)
        {
            var widgetReturnResult = _widgetManager.RenderAdmin(widgetKey, widgetId, layoutId, layoutKeyId,
                ControllerContext, dynamicTitle, containerPageId);
            widgetReturnResult.ErrorMessage = errorMessage;
            widgetReturnResult.SuccessMessage = successMessage;
            return View(MVC.Admin.Widget.Views.ManageWidget, widgetReturnResult);
        }

        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Manage Widgets",
            Key = PermissionKeys.CanManageWidgets)]
        public virtual ActionResult RenderMainWidgetAdmin(string widgetKey, int widgetId, int layoutId, int layoutKeyId,
            string dynamicTitle, int widgetCulture, string successMessage = null, string errorMessage = null)
        {
            var widgetReturnResult = _widgetManager.RenderAdmin(widgetKey, widgetId, layoutId, layoutKeyId,
                ControllerContext, dynamicTitle, -1, widgetCulture);
            widgetReturnResult.ErrorMessage = errorMessage;
            widgetReturnResult.SuccessMessage = successMessage;
            return View(MVC.Admin.Widget.Views.ManageWidget, widgetReturnResult);
        }

        [HttpPost, ValidateInput(false)]
        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Manage Widgets",
            Key = PermissionKeys.CanManageWidgets)]
        public virtual ActionResult UpdateWidget(FormCollection form)
        {
            var widgetData = _widgetManager.GetWidgetData(form);
            var updatedModel = _widgetManager.GenerateExpandoModel(form);
            var widgetReturnResult = _widgetManager.UpdateAdmin(widgetData.WidgetKey, widgetData.WidgetId,
                widgetData.LayoutId, widgetData.LayoutKeyId, ControllerContext, widgetData.DynamicTitle, updatedModel,
                widgetData.ContainerPageId, widgetData.WidgetCulture);
            if (widgetData.Regular)
            {
                return RedirectToAction(MVC.Admin.Widget.ActionNames.RenderWidgetAdmin,
                    new
                    {
                        Area = Constants.DefaultArea,
                        widgetKey = widgetData.WidgetKey,
                        widgetId = widgetData.WidgetId,
                        layoutId = widgetData.LayoutId,
                        layoutKeyId = widgetData.LayoutKeyId,
                        dynamicTitle = widgetData.DynamicTitle,
                        containerPageId = widgetData.ContainerPageId,
                        successMessage = widgetReturnResult.SuccessMessage,
                        errorMessage = widgetReturnResult.ErrorMessage
                    });
            }
            return RedirectToAction(MVC.Admin.Widget.ActionNames.RenderMainWidgetAdmin,
                new
                {
                    Area = Constants.DefaultArea,
                    widgetKey = widgetData.WidgetKey,
                    widgetId = widgetData.WidgetId,
                    layoutId = widgetData.LayoutId,
                    layoutKeyId = widgetData.LayoutKeyId,
                    dynamicTitle = widgetData.DynamicTitle,
                    widgetCulture = widgetData.WidgetCulture,
                    successMessage = widgetReturnResult.SuccessMessage,
                    errorMessage = widgetReturnResult.ErrorMessage
                });
        }

        #region Helpers

        [HttpGet]
        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Manage Widgets",
            Key = PermissionKeys.CanManageWidgets)]
        public virtual JsonResult WidgetList(string filter)
        {
            return Json(_widgetService.WidgetList(filter), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Manage Widgets",
            Key = PermissionKeys.CanManageWidgets)]
        public virtual JsonResult GetActiveWidgets(string filter)
        {
            return Json(_widgetService.WidgetList(filter).Records.Where(x => x.Active), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Add Widgets to Page",
            Key = PermissionKeys.CanAddWidgetsToPage)]
        public virtual JsonResult AddWidgetToPage(int pageId, int layoutId, int elementId, string widgetKey)
        {
            var newWidget = _widgetService.AddWidgetToPage(pageId, layoutId, elementId, widgetKey);
            return Json(newWidget, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Update Widgets on Page",
            Key = PermissionKeys.CanUpdateWidgetsOnPage)]
        public virtual JsonResult UpdateWidgetOnPage(int id, int pageId, int layoutId, int elementId, string widgetKey,
            string orderList)
        {
            _widgetService.UpdateWidgetOnPage(id, pageId, layoutId, elementId, widgetKey, orderList);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [OxideAdminPermission(Group = PermissionKeys.WidgetManagement, Permission = "Can Delete Widgets from Page",
            Key = PermissionKeys.CanDeleteWidgetsFromPage)]
        public virtual JsonResult DeleteWidgetFromPage(int id)
        {
            _widgetService.DeleteWidgetFromPage(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]

Oxide/Oxide/Areas/OxideFundamentals/Controllers/CarouselController.cs
using Oxide.Core.Base.OxideController;
using Oxide.Core.Services.OxideService;

namespace Oxide.Fundamentals.Controllers
{
    public partial class CarouselController : OxideController
    {
        public CarouselController()
        {
        }

        public CarouselController(IOxideServices oxideServices) : base(oxideServices)
        {
        }
    }
}

Oxide/Oxide/Areas/OxideFundamentals/Controllers/LightboxGalleryController.cs
using Oxide.Core.Base.OxideController;
using Oxide.Core.Services.OxideService;

namespace Oxide.Fundamentals.Controllers
{
    public partial class LightboxGalleryController : OxideController
    {
        public LightboxGalleryController()
        {
        }

        public LightboxGalleryController(IOxideServices oxideServices) : base(oxideServices)
        {
        }
    }
}

Oxide/Oxide/Areas/OxideFundamentals/Controllers/SliderController.cs
using Oxide.Core.Base.OxideController;
using Oxide.Core.Services.OxideService;

namespace Oxide.Fundamentals.Controllers
{
    public partial class SliderController : OxideController
    {
        public SliderController()
        {
        }

        public SliderController(IOxideServices oxideServices) : base(oxideServices)
        {
        }
    }
}

Oxide/Oxide/Areas/OxideFundamentals/Views/Widgets/Front/Carousel.cshtml
@using System.Web.Optimization
@using Oxide.Core.Extesions
@using Oxide.Core.Managers.ResourceManager
@Bundler.RenderStyles("~/DefaultTheme/default", new { property = "" })
@Bundler.RenderStyles("~/OxideFundamentals/oxidefundamentals", new { property = "" })

@{
    var carouselId = Guid.NewGuid();
    var carouselName = string.Format(@"#{0}", carouselId);
    var index = 0;
    var indicatorsIndex = 0;
}
<div data-ride="carousel" class="carousel slide" data-interval="@Model.Parameters.Settings.Interval"
     @Model.Parameters.IsPauseOnHover @Model.Parameters.IsWrapSlides @Model.Parameters.IsKeyboardControl
     id="@carouselId">
    <div role="listbox" class="carousel-inner">
        @foreach (var v in @Model.Parameters.Carousels)
        {
            if (index == @Model.Parameters.Settings.StartSlideIndex)
            {
                <div class="item active">
                    <img class="img-responsive carousel-img " src="@v" alt="Slide Image" @Model.Parameters.MaxWidthValue @Model.Parameters.MaxHeightValue/>
                </div>
            }
            else
            {
                <div class="item">
                    <img class="img-responsive carousel-img " src="@v" alt="Slide Image" @Model.Parameters.MaxWidthValue @Model.Parameters.MaxHeightValue/>
                </div>
            }
            index += 1;
        }
    </div>
    <div>
        <a href="@carouselName" role="button" data-slide="prev" class="left carousel-control">
            <i class="glyphicon glyphicon-chevron-left"></i><span class="sr-only"> @Html.T("Previous")</span></a>
        <a href="@carouselName" role="button" data-slide="next" class="right carousel-control">
            <i class="glyphicon glyphicon-chevron-right"></i><span class="sr-only">>@Html.T("Next")</span></a>
    </div>
    @{
        if (@Model.Parameters.Settings.ShowIndicators)
        {
            <ol class="carousel-indicators">
                @foreach (var v in @Model.Parameters.Carousels)
                {
                    if (indicatorsIndex == @Model.Parameters.Settings.StartSlideIndex)
                    {
                        <li data-target="@carouselName" data-slide-to="@indicatorsIndex" class="active"></li>
                    }
                    else
                    {
                        <li data-target="@carouselName" data-slide-to="@indicatorsIndex"></li>
                    }
                    indicatorsIndex += 1;
                }
            </ol>
        }
    }

</div>

@Html.RequireScript("~/bundles/jqueryFront")

Oxide/Oxide/Areas/OxideFundamentals/Views/Widgets/Front/CkEditor.cshtml
<link rel="stylesheet" type="text/css" href="http://cdn.ckeditor.com/4.6.2/full-all/plugins/codesnippet/lib/highlight/styles/obsidian.css" property="">
<script src="http://cdn.ckeditor.com/4.6.2/full-all/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
@Html.Raw(@Model.Parameters)

Oxide/Oxide/Areas/OxideFundamentals/Views/Widgets/Front/CoolMenu.cshtml
@using System.Web.Optimization
@using Oxide.Core.Extesions
@using Oxide.Core.Managers.ResourceManager
@using Oxide.Fundamentals.ViewModels.Menu
@Bundler.RenderStyles("~/OxideFundamentals/oxidefundamentals", new { property = "" })

<div class="coolMenu">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <a href="#" class="navbar-brand navbar-link">
                    <img height="60" src="@Model.Parameters.LogoUrl" id="logo"/>
                </a>
                <button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggle collapsed">
                    <span class="sr-only">@Html.T("Toggle navigation")</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
            </div>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav navbar-right">
                    @if (@Model.Parameters != null)
                    {
                        foreach (var menu in @Model.Parameters.Menus)
                        {
                            @Html.Partial("CoolMenuItem", (CoolMenuViewModel) menu)
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
</div>

@Html.RequireScript("~/bundles/jqueryFront")
@Html.RequireScript("~/bundles/bootstrapFront")

Oxide/Oxide/Areas/OxideFundamentals/Views/Widgets/Front/CultureSelecter.cshtml
@using System.Web.Optimization
@using Oxide.Areas.Admin.Models
@using Oxide.Core.Extesions
@Bundler.RenderStyles("~/OxideFundamentals/oxidefundamentals", new { property = "" })
<div class="cultureSelecter ">
    <div class="navbar-collapse pull-right" style="padding-right: 8px;">
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    @if (@Model.Parameters != null)
                    {
                        @Model.Parameters.ActiveCultureName<b class="caret"></b>
                    }
                </a>
                <ul class="dropdown-menu" style="min-width: 102px;">
                    @if (@Model.Parameters != null)
                    {
                        foreach (Language menu in @Model.Parameters.Languages)
                        {
                            <li>
                                @if (@Model.Parameters != null)
                                {
                                    <a type="submit" href="@Url.Action("ChangeCulture", "Front", new {area = "Oxide.Fundamentals", calture = menu.Code, pageUrl = @Model.Parameters.ActiveUrl})">@menu.Native</a>
                                }
                            </li>
                        }
                    }
                </ul>
            </li>
        </ul>
    </div>
</div>
@Html.RequireScript("~/bundles/jqueryFront")
@Html.RequireScript("~/bundles/bootstrapFront")

Oxide/Oxide/Areas/OxideFundamentals/Views/Widgets/Front/Footer.cshtml
@using System.Web.Optimization
@using Oxide.Core.Extesions
@using Oxide.Fundamentals.ViewModels.Footer
@Bundler.RenderStyles("~/OxideFundamentals/oxidefundamentals", new { property = "" })
@Bundler.RenderStyles("~/DefaultTheme/fontawesome", new { property = "" })
@{
    var footerModel = (FooterWidgetViewModel) @Model.Parameters;
}
<div class="footer-clean">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-push-6 item text">
                    @if (footerModel != null)
                    {
                        <h3>@footerModel.Name</h3>
                    }
                    @if (footerModel != null)
                    {
                        <p>@footerModel.Description</p>
                    }
                </div>
                @if (footerModel != null)
                {
                    foreach (var menu in @footerModel.MenuItemListFront)
                    {
                        <div class="col-md-2 col-md-pull-6 col-sm-4 item footerLinkItem">
                            <h3>
                                <a class="footerLink" href="@menu.Url" target="@menu.Target">@menu.Name</a>
                            </h3>
                            <ul>
                                @foreach (var subMenu in menu.SubMenus)
                                {
                                    <li>
                                        <a href="@subMenu.Url" target="@subMenu.Target">@subMenu.Name</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    }
                }
            </div>
            <div class="row">
                @if (footerModel != null)
                {
                    <div class="col-md-12 col-sm-4 item social">
                        <a href="@footerModel.FacebookLink">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a href="@footerModel.TwiterLink">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a href="@footerModel.LinkedInLink">
                            <i class="fa fa-linkedin"></i>
                        </a>
                    </div>
                }
            </div>
            @if (footerModel != null)
            {
                <p class="copyright">@footerModel.CopyRight</p>
            }
        </div>
    </footer>
</div>

Oxide/Oxide/Areas/OxideFundamentals/Views/Widgets/Front/FooterDark.cshtml
@using System.Web.Optimization
@using Oxide.Core.Extesions
@using Oxide.Fundamentals.ViewModels.Footer
@Bundler.RenderStyles("~/OxideFundamentals/oxidefundamentals", new { property = "" })
@Bundler.RenderStyles("~/DefaultTheme/fontawesome", new { property = "" })
@{
    var footerModel = (FooterWidgetViewModel) @Model.Parameters;
}
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-push-6 item text">
                    @if (footerModel != null)
                    {
                        <h3>@footerModel.Name</h3>
                    }
                    @if (footerModel != null)
                    {
                        <p>@footerModel.Description</p>
                    }
                </div>
                @if (footerModel != null)
                {
                    foreach (var menu in @footerModel.MenuItemListFront)
                    {
                        <div class="col-md-2 col-md-pull-6 col-sm-4 item footerLinkItem">
                            <h3>
                                <a class="footerLink" href="@menu.Url" target="@menu.Target">@menu.Name</a>
                            </h3>
                            <ul>
                                @foreach (var subMenu in menu.SubMenus)
                                {
                                    <li>
                                        <a href="@subMenu.Url" target="@subMenu.Target">@subMenu.Name</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    }
                }
            </div>
            <div class="row">
                @if (footerModel != null)
                {
                    <div class="col-md-12 col-sm-4 item social">
                        <a href="@footerModel.FacebookLink">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a href="@footerModel.TwiterLink">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a href="@footerModel.LinkedInLink">
                            <i class="fa fa-linkedin"></i>
                        </a>
                    </div>
                }
            </div>
            @if (footerModel != null)
            {
                <p class="copyright">@footerModel.CopyRight</p>
            }
        </div>
    </footer>
</div>

Oxide/Oxide/Areas/OxideFundamentals/Views/Widgets/Front/LightboxGallery.cshtml
@using System.Web.Optimization
@using Oxide.Core.Extesions
@using Oxide.Core.Managers.ResourceManager
@Bundler.RenderStyles("~/OxideFundamentals/lightbox", new { property = "" })

@{
    var lightBoxGalleryId = Guid.NewGuid();
}
<div id="@lightBoxGalleryId" class="photo-gallery">
    <div class="row photos">
        @foreach (var v in @Model.Parameters)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 item img-responsive">
                <a href="@v" data-lightbox="photos">
                    <img class="img-responsive" src="@v" alt="gallery"/>
                </a>
            </div>
        }
    </div>
</div>
@Html.GetJsonResources(new[] {"Oxide.Fundamentals"}, "Gallery")
@Html.RequireScript("~/bundles/jqueryFront")
@Html.RequireScript("~/bundles/bootstrapFront")
@Html.RequireScript("~/bundles/lightbox")

Oxide/Oxide/Areas/OxideFundamentals/Views/Widgets/Front/NavigationMenu.cshtml
@using System.Web.Optimization
@using Oxide.Core.Extesions
@using Oxide.Core.Managers.ResourceManager
@using Oxide.Fundamentals.ViewModels.Menu
@Bundler.RenderStyles("~/OxideFundamentals/oxidefundamentals", new { property = "" })

<div>
    <nav class="navbar navbar-default navigation-clean">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1">
                <span class="sr-only">@Html.T("Toggle navigation")</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        </div>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="nav navbar-nav">
                @if (@Model.Parameters != null)
                {
                    foreach (var menu in @Model.Parameters)
                    {
                        @Html.Partial("MenuItem", (NavigationMenuViewModel) menu)
                    }
                }
            </ul>
        </div>
    </nav>
</div>
@Html.RequireScript("~/bundles/jqueryFront")
@Html.RequireScript("~/bundles/bootstrapFront")