Oxide/Oxide/Areas/Oxide.Extra/Models/Timeline/TimelineItem.cs
using Oxide.Core.Base.OxideAttributes;
using Oxide.Core.Base.OxideDataBaseModel;

namespace Oxide.Extra.Models.Timeline
{
    [OxideDatabase("OxideExtraContext")]
    public class TimelineItem : OxideDatabaseModel, IOxideDataBaseModel
    {
        public string Description { get; set; }
        public int ImageId { get; set; }
    }
}

Oxide/Oxide/Areas/Oxide.Extra/Models/Timeline/TimelineWidget.cs
using System.Collections.Generic;
using Oxide.Core.Base.OxideAttributes;
using Oxide.Core.Base.OxideDataBaseModel;

namespace Oxide.Extra.Models.Timeline
{
    [OxideDatabase("OxideExtraContext")]
    public class TimelineWidget : OxideDatabaseModel, IOxideDataBaseModel
    {
        public int Key { get; set; }
        public virtual ICollection<TimelineWidgetItem> TimelineItems { get; set; }
    }
}

Oxide/Oxide/Areas/Oxide.Extra/Models/Timeline/TimelineWidgetItem.cs
using Oxide.Core.Base.OxideAttributes;
using Oxide.Core.Base.OxideDataBaseModel;

namespace Oxide.Extra.Models.Timeline
{
    [OxideDatabase("OxideExtraContext")]
    public class TimelineWidgetItem : OxideDatabaseModel, IOxideDataBaseModel
    {
        public virtual int TimelineWidgetId { get; set; }
        public virtual int TimelineItemId { get; set; }
    }
}

Oxide/Oxide/Areas/Oxide.Extra/ViewModels/Timeline/TimelineItemFrontViewModel.cs
using Oxide.Core.Base.OxideViewModel;

namespace Oxide.Extra.ViewModels.Timeline
{
    public class TimelineItemFrontViewModel : OxideViewModel
    {
        public string Description { get; set; }
        public string ImagePath { get; set; }
    }
}

Oxide/Oxide/Areas/Oxide.Extra/ViewModels/Timeline/TimelineItemViewModel.cs
using Oxide.Core.Base.OxideViewModel;

namespace Oxide.Extra.ViewModels.Timeline
{
    public class TimelineItemViewModel : OxideWidgetViewModel
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public int ImageId { get; set; }
        public string ImagePath { get; set; }
        public string ActiveUrl { get; set; }
    }
}

Oxide/Oxide/Areas/Oxide.Extra/ViewModels/Timeline/TimelineWidgetFrontViewModel.cs
using System.Collections.Generic;
using Oxide.Core.Base.OxideViewModel;

namespace Oxide.Extra.ViewModels.Timeline
{
    public class TimelineWidgetFrontViewModel : OxideViewModel
    {
        public virtual ICollection<TimelineItemFrontViewModel> TeamMemberItems { get; set; }
    }
}

Oxide/Oxide/Areas/Oxide.Extra/ViewModels/Timeline/TimelineWidgetViewModel.cs
using Oxide.Core.Base.OxideViewModel;

namespace Oxide.Extra.ViewModels.Timeline
{
    public class TimelineWidgetViewModel : OxideWidgetViewModel
    {
        public string Key { get; set; }
        public string TimelineItems { get; set; }
        public string ActiveUrl { get; set; }
        public string Title { get; set; }
    }
}

Oxide/Oxide/Areas/Oxide.Extra/Controllers/TimelineController.cs
using System;
using System.Web.Mvc;
using Oxide.Core.Base.OxideAttributes;
using Oxide.Core.Base.OxideController;
using Oxide.Core.Models.Base;
using Oxide.Core.Services.OxideService;
using Oxide.Core.Syntax;
using Oxide.Extra.Keywords;
using Oxide.Extra.Models.Timeline;
using Oxide.Extra.Services.Interface;
using Oxide.Extra.ViewModels.Timeline;

namespace Oxide.Extra.Controllers
{
    public class TimelineController : OxideController
    {
        private readonly ITimelineWidgetService _timelineWidgetService;

        public TimelineController()
        {
        }

        public TimelineController(IOxideServices oxideServices, ITimelineWidgetService timelineWidgetService)
            : base(oxideServices)
        {
            _timelineWidgetService = timelineWidgetService;
        }

        [OxideAdmin]
        [OxideAdminPermission(Group = "Teamline Widget", Permission = "Can Display Timeline Item",
            Key = "Can_Display_Timeline_Items")]
        public ActionResult DisplayTimelineItems()
        {
            return
                View(new OxideModel
                {
                    RequestType = Syntax.Requests.Static,
                    Header = OxideServices.GetText("Team Members"),
                    Title = Constants.Empty
                });
        }

        [OxideAdmin]
        [OxideAdminPermission(Group = "Teamline Widget", Permission = "Can Create Timeline Items",
            Key = "Can_Create_Timeline_Items")]
        public ActionResult CreateTimelineItem()
        {
            var timelineItemViewModel = new TimelineItemViewModel {ActiveUrl = HttpContext.Request.RawUrl};
            return
                View(new OxideModel
                {
                    RequestType = Syntax.Requests.Static,
                    Header = OxideServices.GetText("Timeline Items"),
                    Title = OxideServices.GetText("Create Timeline Item"),
                    Parameters = timelineItemViewModel
                });
        }

        [OxideAdmin]
        [OxideAdminPermission(Group = "Teamline Widget", Permission = "Can Create Timeline Items",
            Key = "Can_Create_Timeline_Items")]
        public ActionResult SaveTeamlineItem(string mediaSelecter, string pageUrl, string dateTitle, string title,
            string description)
        {
            var timelineItem = new TimelineItem
            {
                Name = dateTitle,
                Title = title,
                Description = description,
                ImageId = Convert.ToInt32(mediaSelecter)
            };
            var createTeamMember = _timelineWidgetService.CreateTimelineItem(timelineItem);
            var oxideModel = new OxideModel {RequestType = Syntax.Requests.Static};
            if (createTeamMember)
                oxideModel.SuccessMessage = OxideServices.GetText("Timeline item saved successfully");
            else
                oxideModel.ErrorMessage =
                    OxideServices.GetText(
                        "Problem while saving timeline item, operation is not succesfull, please check the logs");
            TempData[Keys.TimelineItem] = oxideModel;
            return Redirect(pageUrl);
        }

        [OxideAdmin]
        [OxideAdminPermission(Group = "Teamline Widget", Permission = "Can Edit Timeline Items",
            Key = "Can_Edit_Timeline_Items")]
        public ActionResult EditTimelineItem(int id)
        {
            var teamMeber = _timelineWidgetService.GetTimelineItem(id);
            if (teamMeber == null) return RedirectToAction("DisplayTimelineItems");
            var teamMemberItemViewModel = new TimelineItemViewModel
            {
                Id = id,
                Name = teamMeber.Name,
                Title = teamMeber.Title,
                Description = teamMeber.Description,
                ActiveUrl = HttpContext.Request.RawUrl,
                ImageId = teamMeber.ImageId
            };
            return
                View(new OxideModel
                {
                    RequestType = Syntax.Requests.Static,
                    Header = OxideServices.GetText("Timeline Items"),
                    Title = OxideServices.GetText("Edit Timeline Item"),
                    Parameters = teamMemberItemViewModel
                });
        }

        [OxideAdmin]
        [OxideAdminPermission(Group = "Teamline Widget", Permission = "Can Edit Timeline Items",
            Key = "Can_Edit_Timeline_Items")]
        public ActionResult UpdateTeamline(int id, string mediaSelecter, string pageUrl, string dateTitle, string title,
            string description)
        {
            var teamMemberItem = new TimelineItem
            {
                Id = id,
                Name = dateTitle,
                Title = title,
                Description = description,
                ImageId = Convert.ToInt32(mediaSelecter)
            };
            var updateTeamMember = _timelineWidgetService.UpdateTimelineItem(teamMemberItem);
            var oxideModel = new OxideModel {RequestType = Syntax.Requests.Static};
            if (updateTeamMember)
                oxideModel.SuccessMessage = OxideServices.GetText("Timeline item updated successfully");
            else
                oxideModel.ErrorMessage =
                    OxideServices.GetText(
                        "Problem while updating timeline item, operation is not succesfull, please check the logs");
            TempData[Keys.TimelineItem] = oxideModel;
            return Redirect(pageUrl);
        }

        [HttpGet]
        [OxideAdminPermission(Group = "Teamline Widget", Permission = "Can Display Teamline Items",
            Key = "Can_Display_Timeline_Items")]
        public virtual JsonResult DeleteTimelineItem(int id)
        {
            _timelineWidgetService.DeleteTimelineItem(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }
}

Oxide/Oxide/Areas/Oxide.Extra/Views/Timeline/CreateTimelineItem.cshtml
@using Oxide.Core.Engines
@using Oxide.Core.Managers.ResourceManager
@using Oxide.Core.Models.Base
@using Oxide.Extra.Keywords
<!-- Action Message -->
@{
    var modelx = TempData[Keys.TimelineItem] as OxideModel;
}
@if (modelx != null)
{
    if (modelx.SuccessMessage != string.Empty)
    {
        <h5 class="successMessage">@modelx.SuccessMessage </h5>
    }
    if (modelx.ErrorMessage != string.Empty)
    {
        <h5 class="errorMessage">@modelx.ErrorMessage </h5>
    }
}
<!-- /Action Message -->
@using (Html.BeginForm("SaveTeamlineItem", "Timeline", new {area = "Oxide.Extra"}, FormMethod.Post, new {@class = "form-horizontal form-label-left"}))
{
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="dateTitle">
            @Html.T("Date Title") <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="dateTitle" class="form-control col-md-7 col-xs-12" value="@Model.Parameters.Name" data-validate-length-range="6" data-validate-words="1" name="dateTitle" required="required" type="text">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">
            @Html.T("Title") <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="title" class="form-control col-md-7 col-xs-12" value="@Model.Parameters.Title" data-validate-length-range="6" data-validate-words="1" name="title" type="text">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">
            @Html.T("Description")
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <textarea id="description" name="description" class="form-control col-md-7 col-xs-12">@Model.Parameters.Description</textarea>
        </div>
    </div>
    <div class="item form-group">
        <div class="col-md-6 col-sm-6 col-xs-12">
            @if ((Model.Parameters.ImageId != null))
            {
                @Oxd.RenderMediaSelecter("mediaSelecter", false, @Model.Parameters.ImageId.ToString())
            }
            else
            {
                @Oxd.RenderMediaSelecter("mediaSelecter")
            }

        </div>
    </div>
    <input type="hidden" id="pageUrl" name="pageUrl" value="@Model.Parameters.ActiveUrl">
    <button id="send" type="submit" class="btn btn-dark">
        <i class="fa fa-check"></i> @Html.T("Save")
    </button>
}

Oxide/Oxide/Areas/Oxide.Extra/Views/Timeline/DisplayTimelineItems.cshtml
@using Oxide.Core.Engines
@using Oxide.Extra.Models.Timeline
@Oxd.RenderDataList(typeof (TimelineItem).Name, Url.Action("EditTimelineItem", "Timeline", new {area = "Oxide.Extra"}), Url.Action("DeleteTimelineItem", "Timeline", new {area = "Oxide.Extra"}), null, "Name,Title", null, true, "ImageId")

Oxide/Oxide/Areas/Oxide.Extra/Views/Timeline/EditTimelineItem.cshtml
@using Oxide.Core.Engines
@using Oxide.Core.Managers.ResourceManager
@using Oxide.Core.Models.Base
@using Oxide.Extra.Keywords
<!-- Action Message -->
@{
    var modelx = TempData[Keys.TimelineItem] as OxideModel;
}
@if (modelx != null)
{
    if (modelx.SuccessMessage != string.Empty)
    {
        <h5 class="successMessage">@modelx.SuccessMessage </h5>
    }
    if (modelx.ErrorMessage != string.Empty)
    {
        <h5 class="errorMessage">@modelx.ErrorMessage </h5>
    }
}
<!-- /Action Message -->
@using (Html.BeginForm("UpdateTeamline", "Timeline", new {area = "Oxide.Extra"}, FormMethod.Post, new {@class = "form-horizontal form-label-left"}))
{
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="dateTitle">
            @Html.T("Date Title") <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="dateTitle" class="form-control col-md-7 col-xs-12" value="@Model.Parameters.Name" data-validate-length-range="6" data-validate-words="1" name="dateTitle" required="required" type="text">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">
            @Html.T("Title") <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="title" class="form-control col-md-7 col-xs-12" value="@Model.Parameters.Title" data-validate-length-range="6" data-validate-words="1" name="title" type="text">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">
            @Html.T("Description")
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <textarea id="description" name="description" class="form-control col-md-7 col-xs-12">@Model.Parameters.Description</textarea>
        </div>
    </div>
    <div class="item form-group">
        <div class="col-md-6 col-sm-6 col-xs-12">
            @if ((Model.Parameters.ImageId != null))
            {
                @Oxd.RenderMediaSelecter("mediaSelecter", false, @Model.Parameters.ImageId.ToString())
            }
            else
            {
                @Oxd.RenderMediaSelecter("mediaSelecter")
            }

        </div>
    </div>
    <input type="hidden" id="pageUrl" name="pageUrl" value="@Model.Parameters.ActiveUrl">
    <input type="hidden" id="id" name="id" value="@Model.Parameters.Id">
    <button id="send" type="submit" class="btn btn-dark right">
        <i class="fa fa-check"></i> @Html.T("Update")
    </button>
}